# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin

# 2 - 5 elemanlı bir numpy array oluşturun

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
import numpy as np
array = np.array([6, 4, 5, 20, 24])
print("array:", array)
kucuktenBuyuge = np.sort(array)
print("Kucukten buyuge dogru siralanmis array:",kucuktenBuyuge)



array: [ 6  4  5 20 24]
Kucukten buyuge dogru siralanmis array: [ 4  5  6 20 24]


# Problem 2

In [4]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
array1 = np.array([10, 15, 30, 45, 60])
print("dizi1:", array1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5, 16)
print("dizi22:", array2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50, 101, 5)
print("dizi3:", array3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)
print("dizi4:", array4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)
print("dizi5:", array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6 = np.linspace(0, 100, 5)
print("dizi6:", array6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7 = np.random.randint(10, 31, size=5)
print("dizi7:", array7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8 = np.random.uniform(-1, 1, size=10)
print("dizi8:", array8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix = np.random.randint(10, 51, size=(3, 5))
print("matris:\n", matrix)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satirlar,sütunlar = matrix.shape
print("satşr sayisi:", satirlar)
print("sütun sayisi:", sütunlar)
print("toplam:", satirlar + sütunlar)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
maxDeger = np.max(matrix)
minDeger = np.min(matrix)
ortDeger = np.mean(matrix)
print("en büyük deger:", maxDeger)
print("en kücük deger:", minDeger)
print("ortalama:", ortDeger)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
maxIndex = np.argmax(matrix)
print("en büyük değerin indeksi:", maxIndex)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array13 = np.arange(10, 21)
print("ilk 3 eleman:", array13[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("tersten hali:", array13[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
ilkSatir= matrix[0]
print("ilk satir:",ilkSatir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman = matrix[1,2]
print("2.satir 3. sütundaki eleman:", eleman)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilkElemanlar = matrix[:, 0]
print("tum satirlardaki ilk elemanlar:",ilkElemanlar)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
elemanlarinKareleri = np.power(matrix, 2)
print("elemanlarinin karesi:",elemanlarinKareleri)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrixx = np.random.randint(-50, 51, size=(3, 5))
pozitifCift = matrixx[(matrixx > 0) & (matrixx % 2 == 0)]
print("pozitif cift sayilar:",pozitifCift)


dizi1: [10 15 30 45 60]
dizi22: [ 5  6  7  8  9 10 11 12 13 14 15]
dizi3: [ 50  55  60  65  70  75  80  85  90  95 100]
dizi4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
dizi5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
dizi6: [  0.  25.  50.  75. 100.]
dizi7: [10 20 10 18 16]
dizi8: [-0.72715624  0.01995221  0.97947822 -0.39581759 -0.8866614  -0.89413015
 -0.05959952 -0.94913608  0.48335859 -0.2633138 ]
matris:
 [[39 17 50 14 33]
 [18 43 37 44 19]
 [10 42 49 15 33]]
satşr sayisi: 3
sütun sayisi: 5
toplam: 8
en büyük deger: 50
en kücük deger: 10
ortalama: 30.866666666666667
en büyük değerin indeksi: 2
ilk 3 eleman: [10 11 12]
tersten hali: [20 19 18 17 16 15 14 13 12 11 10]
ilk satir: [39 17 50 14 33]
2.satir 3. sütundaki eleman: 37
tum satirlardaki ilk elemanlar: [39 18 10]
elemanlarinin karesi: [[1521  289 2500  196 1089]
 [ 324 1849 1369 1936  361]
 [ 100 1764 2401  225 1089]]
pozitif cift sayilar: [26 20 42 26  4 42]
